import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import NavBar from "@components/HomeNavBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Worksheesh</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <NavBar />
      <main>
        <div className="hero min-h-screen bg-base-200">
          <div className="hero-content flex-col lg:flex-row">
            <div className="mr-8">
              <h1 className="text-5xl font-bold">Box Office News!</h1>
              <p className="py-6 text-lg">
                Provident cupiditate voluptatem et in. Quaerat fugiat ut
                assumenda excepturi exercitationem quasi. In deleniti eaque aut
                repudiandae et a id nisi.
              </p>
              <Link href="/sign-in">
                <button className="btn-primary btn">Get Started</button>
              </Link>
            </div>
            <Image
              src="/images/hero.jpg"
              alt="Hero Image"
              width="800"
              height="600"
              className=" rounded-lg shadow-2xl"
            />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
