import { signIn } from "next-auth/react";

import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NavBar from "@components/HomeNavBar";
import { useSession } from "next-auth/react";
import { api } from "../utils/api";

const MyWorksheets: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Worksheets - Worksheesh</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </>
  );
};

export default MyWorksheets;

const NavActions: React.FC = () => {
  const { data: profiles, refetch: refetchProfiles } =
    api.teacherProfile.getAll.useQuery(
      undefined // no input
    );

  if (profiles?.length == 0) {
    const createProfile = api.teacherProfile.create.useMutation({
      onSuccess: () => {
        void refetchProfiles();
      },
    });

    createProfile.mutate();
  }

  return (
    <WorksheetList profileId={profiles?.at(0)?.id as string}></WorksheetList>
  );
};

interface Props {
  profileId: string;
}

const WorksheetList: React.FC<Props> = ({ profileId }) => {
  const { data: worksheets, refetch: refetchWorksheets } =
    api.worksheet.getByProfile.useQuery({
      profileId: profileId,
    });

  if (worksheets?.length == 0) {
    return <></>;
  } else {
    return <></>;
  }
};
