import { signIn } from "next-auth/react";

import { type NextPage } from "next";
import Head from "next/head";

import NavBar from "@components/HomeNavBar";

const SignIn: NextPage<Props> = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <button className="btn-primary btn" onClick={() => void signIn("zoom")}>
          Sign In With Zoom
        </button>
      </main>
    </>
  );
};

export default SignIn;
